export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL";

export const REQUEST_HISTORY_LIST_REQUEST = "REQUEST_HISTORY_LIST_REQUEST";
export const REQUEST_HISTORY_LIST_SUCCESS = "REQUEST_HISTORY_LIST_SUCCESS";
export const REQUEST_HISTORY_LIST_FAIL = "REQUEST_HISTORY_LIST_FAIL";

export const REQUEST_MY_LIST_REQUEST = "REQUEST_MY_LIST_REQUEST";
export const REQUEST_MY_LIST_SUCCESS = "REQUEST_MY_LIST_SUCCESS";
export const REQUEST_MY_LIST_FAIL = "REQUEST_MY_LIST_FAIL";

export const REQUEST_UPDATE_REQUEST = "REQUEST_UPDATE_REQUEST";
export const REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
export const REQUEST_UPDATE_FAIL = "REQUEST_UPDATE_FAIL";
export const REQUEST_UPDATE_RESET = "REQUEST_UPDATE_RESET";

export const REQUEST_CREATE_REQUEST = "REQUEST_CREATE_REQUEST";
export const REQUEST_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
export const REQUEST_CREATE_FAIL = "REQUEST_CREATE_FAIL";
export const REQUEST_CREATE_RESET = "REQUEST_CREATE_RESET";

export const REQUEST_DELETE_REQUEST = "REQUEST_DELETE_REQUEST";
export const REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";
export const REQUEST_DELETE_FAIL = "    REQUEST_DELETE_FAIL";

export const REQUEST_DETAIL_REQUEST = "REQUEST_DETAIL_REQUEST";
export const REQUEST_DETAIL_SUCCESS = "REQUEST_DETAIL_SUCCESS";
export const REQUEST_DETAIL_FAIL = "REQUEST_DETAIL_FAIL";

export const REQUEST_COMMENT_REQUEST = "REQUEST_COMMENT_REQUEST";
export const REQUEST_COMMENT_SUCCESS = "REQUEST_COMMENT_SUCCESS";
export const REQUEST_COMMENT_FAIL = "REQUEST_COMMENT_FAIL";

export const REQUEST_STAFF_REQUEST = "REQUEST_STAFF_REQUEST";
export const REQUEST_STAFF_SUCCESS = "REQUEST_STAFF_SUCCESS";
export const REQUEST_STAFF_FAIL = "REQUEST_STAFF_FAIL";

export const REQUEST_APPROVAL_REQUEST = "REQUEST_APPROVAL_REQUEST";
export const REQUEST_APPROVAL_SUCCESS = "REQUEST_APPROVAL_SUCCESS";
export const REQUEST_APPROVAL_FAIL = "REQUEST_APPROVAL_FAIL";

export const REQUEST_REJECT_REQUEST = "REQUEST_REJECT_REQUEST";
export const REQUEST_REJECT_SUCCESS = "REQUEST_REJECT_SUCCESS";
export const REQUEST_REJECT_FAIL = "REQUEST_REJECT_FAIL";
